<?php
/**
 * SearchQuerySearchAggregationsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  RSearch\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ParallelStack RSearch API
 *
 * REST API Specification for ParallelStack RSearch API
 *
 * OpenAPI spec version: 1.1.0
 * Contact: team@parallelstack.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace RSearch\Client;

/**
 * SearchQuerySearchAggregationsTest Class Doc Comment
 *
 * @category    Class */
// * @description SearchQuerySearchAggregations
/**
 * @package     RSearch\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SearchQuerySearchAggregationsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SearchQuerySearchAggregations"
     */
    public function testSearchQuerySearchAggregations()
    {
    }

    /**
     * Test attribute "fieldName"
     */
    public function testPropertyFieldName()
    {
    }

    /**
     * Test attribute "aggType"
     */
    public function testPropertyAggType()
    {
    }

    /**
     * Test attribute "termAggSize"
     */
    public function testPropertyTermAggSize()
    {
    }

    /**
     * Test attribute "range"
     */
    public function testPropertyRange()
    {
    }

    /**
     * Test attribute "origin"
     */
    public function testPropertyOrigin()
    {
    }

    /**
     * Test attribute "buckets"
     */
    public function testPropertyBuckets()
    {
    }
}
