<?php
/**
 * RsearchApiTest
 * PHP version 5
 *
 * @category Class
 * @package  RSearch\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ParallelStack RSearch API
 *
 * REST API Specification for ParallelStack RSearch API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: team@parallelstack.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace RSearch\Client;

use \RSearch\Client\Configuration;
use \RSearch\Client\ApiClient;
use \RSearch\Client\ApiException;
use \RSearch\Client\ObjectSerializer;

/**
 * RsearchApiTest Class Doc Comment
 *
 * @category Class
 * @package  RSearch\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RsearchApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addDocument
     *
     * .
     *
     */
    public function testAddDocument()
    {
    }

    /**
     * Test case for addDocumentType
     *
     * .
     *
     */
    public function testAddDocumentType()
    {
    }

    /**
     * Test case for addIndex
     *
     * .
     *
     */
    public function testAddIndex()
    {
    }

    /**
     * Test case for deleteDocument
     *
     * .
     *
     */
    public function testDeleteDocument()
    {
    }

    /**
     * Test case for deleteIndex
     *
     * .
     *
     */
    public function testDeleteIndex()
    {
    }

    /**
     * Test case for getAdvancedSearchResults
     *
     * .
     *
     */
    public function testGetAdvancedSearchResults()
    {
    }

    /**
     * Test case for getAllDocumentTypes
     *
     * .
     *
     */
    public function testGetAllDocumentTypes()
    {
    }

    /**
     * Test case for getAllDocuments
     *
     * .
     *
     */
    public function testGetAllDocuments()
    {
    }

    /**
     * Test case for getAllIndexes
     *
     * .
     *
     */
    public function testGetAllIndexes()
    {
    }

    /**
     * Test case for getBasicSearchResults
     *
     * .
     *
     */
    public function testGetBasicSearchResults()
    {
    }

    /**
     * Test case for getDocument
     *
     * .
     *
     */
    public function testGetDocument()
    {
    }

    /**
     * Test case for getDocumentType
     *
     * .
     *
     */
    public function testGetDocumentType()
    {
    }

    /**
     * Test case for getIndex
     *
     * .
     *
     */
    public function testGetIndex()
    {
    }

    /**
     * Test case for getSuggestResults
     *
     * .
     *
     */
    public function testGetSuggestResults()
    {
    }
}
